<?php /* #?ini charset="utf-8"?

[ClassSearchFormSettings]
DisabledAttributes[]=comunicato/titolo
DisabledAttributes[]=comunicato/sottotitolo
DisabledAttributes[]=comunicato/occhiello
DisabledAttributes[]=comunicato/luogo
DisabledAttributes[]=comunicato/abstract
DisabledAttributes[]=comunicato/testo_completo
DisabledAttributes[]=comunicato/immagini
DisabledAttributes[]=comunicato/audio
DisabledAttributes[]=comunicato/argomento
DisabledAttributes[]=comunicato/numero
DisabledAttributes[]=comunicato/rilevanza

DisabledAttributes[]=news/titolo
DisabledAttributes[]=news/sottotitolo
DisabledAttributes[]=news/occhiello
DisabledAttributes[]=news/luogo
DisabledAttributes[]=news/abstract
DisabledAttributes[]=news/testo_completo
DisabledAttributes[]=news/immagini
DisabledAttributes[]=news/argomento
DisabledAttributes[]=news/numero
DisabledAttributes[]=news/rilevanza
DisabledAttributes[]=news/persone
DisabledAttributes[]=news/fonte

DisabledAttributes[]=deliberazione/data_pubblicazione
DisabledAttributes[]=deliberazione/data_esecutivita
DisabledAttributes[]=deliberazione/data_pubblicazione
DisabledAttributes[]=deliberazione/data_archiviazione
DisabledAttributes[]=deliberazione/numero_seduta
DisabledAttributes[]=deliberazione/riferimento
DisabledAttributes[]=deliberazione/provvedimenti_collegati
DisabledAttributes[]=deliberazione/classificazione_tipologia
DisabledAttributes[]=deliberazione/tipo_decreto
DisabledAttributes[]=deliberazione/codice_struttura_competente
DisabledAttributes[]=deliberazione/tipologia_trasparenza
DisabledAttributes[]=deliberazione/data
DisabledAttributes[]=deliberazione/numero_protocollo
DisabledAttributes[]=deliberazione/esito
  
DisabledAttributes[]=determinazione/data_pubblicazione
DisabledAttributes[]=determinazione/data_esecutivita
DisabledAttributes[]=determinazione/data_pubblicazione
DisabledAttributes[]=determinazione/data_archiviazione
DisabledAttributes[]=determinazione/numero_seduta
DisabledAttributes[]=determinazione/riferimento
DisabledAttributes[]=determinazione/provvedimenti_collegati
DisabledAttributes[]=determinazione/classificazione_tipologia
DisabledAttributes[]=determinazione/tipo_decreto
DisabledAttributes[]=determinazione/codice_struttura_competente
DisabledAttributes[]=determinazione/tipologia_trasparenza
DisabledAttributes[]=determinazione/esito
DisabledAttributes[]=determinazione/data
DisabledAttributes[]=determinazione/numero_protocollo

DisabledAttributes[]=agenzia/competenza
DisabledAttributes[]=agenzia/data_pubblicazione
DisabledAttributes[]=agenzia/data_esecutivita
DisabledAttributes[]=agenzia/data_pubblicazione
DisabledAttributes[]=agenzia/data_archiviazione
DisabledAttributes[]=agenzia/numero_seduta
DisabledAttributes[]=agenzia/riferimento
DisabledAttributes[]=agenzia/provvedimenti_collegati
DisabledAttributes[]=agenzia/classificazione_tipologia
DisabledAttributes[]=agenzia/tipo_decreto
DisabledAttributes[]=agenzia/codice_struttura_competente
DisabledAttributes[]=agenzia/tipologia_trasparenza
DisabledAttributes[]=agenzia/esito 
DisabledAttributes[]=agenzia/data
DisabledAttributes[]=agenzia/numero_protocollo
DisabledAttributes[]=agenzia/allegati
DisabledAttributes[]=agenzia/servizio
DisabledAttributes[]=agenzia/proponente
DisabledAttributes[]=agenzia/tipologia_agenzia

DisabledAttributes[]=decreto/competenza
DisabledAttributes[]=decreto/data_pubblicazione
DisabledAttributes[]=decreto/data_esecutivita
DisabledAttributes[]=decreto/data_pubblicazione
DisabledAttributes[]=decreto/data_archiviazione
DisabledAttributes[]=decreto/numero_seduta
DisabledAttributes[]=decreto/riferimento
DisabledAttributes[]=decreto/provvedimenti_collegati
DisabledAttributes[]=decreto/classificazione_tipologia
DisabledAttributes[]=decreto/tipo_decreto
DisabledAttributes[]=decreto/codice_struttura_competente
DisabledAttributes[]=decreto/tipologia_trasparenza
DisabledAttributes[]=decreto/esito 
DisabledAttributes[]=decreto/data
DisabledAttributes[]=decreto/numero_protocollo
DisabledAttributes[]=decreto/allegati
DisabledAttributes[]=decreto/servizio
DisabledAttributes[]=decreto/proponente



DisabledAttributes[]=persona/email
DisabledAttributes[]=persona/fax
DisabledAttributes[]=persona/matricola
DisabledAttributes[]=persona/numero_breve
DisabledAttributes[]=persona/telefono
DisabledAttributes[]=persona/telefono2
DisabledAttributes[]=persona/telefono3
DisabledAttributes[]=persona/titolo

[RemoteClassSearchFormSettings]
DisabledAttributes[]
DisabledAttributes[]=deliberazione/data
DisabledAttributes[]=deliberazione/data_pubblicazione
DisabledAttributes[]=deliberazione/data_esecutivita
DisabledAttributes[]=deliberazione/informazioni_esecutivita
DisabledAttributes[]=deliberazione/data_archiviazione
DisabledAttributes[]=deliberazione/stato
DisabledAttributes[]=deliberazione/pubblicazione
DisabledAttributes[]=deliberazione/numero_protocollo
DisabledAttributes[]=deliberazione/testo
DisabledAttributes[]=deliberazione/proponente
DisabledAttributes[]=deliberazione/numero_seduta
DisabledAttributes[]=deliberazione/riferimento
DisabledAttributes[]=deliberazione/provvedimenti_collegati
DisabledAttributes[]=deliberazione/classificazione_tipologia
DisabledAttributes[]=deliberazione/tipologia_trasparenza
DisabledAttributes[]=deliberazione/tipo_decreto
# -- Campi da escludere per determinazioni
DisabledAttributes[]=determinazione/data
DisabledAttributes[]=determinazione/data_pubblicazione
DisabledAttributes[]=determinazione/data_esecutivita
DisabledAttributes[]=determinazione/informazioni_esecutivita
DisabledAttributes[]=determinazione/data_archiviazione
DisabledAttributes[]=determinazione/stato
DisabledAttributes[]=determinazione/pubblicazione
DisabledAttributes[]=determinazione/numero_protocollo
DisabledAttributes[]=determinazione/testo
DisabledAttributes[]=determinazione/proponente
DisabledAttributes[]=determinazione/numero_seduta
DisabledAttributes[]=determinazione/riferimento
DisabledAttributes[]=determinazione/provvedimenti_collegati
DisabledAttributes[]=determinazione/classificazione_tipologia
DisabledAttributes[]=determinazione/tipologia_trasparenza
DisabledAttributes[]=determinazione/tipo_decreto
# -- Campi da escludere per decreti
DisabledAttributes[]=decreto/data
DisabledAttributes[]=decreto/data_pubblicazione
DisabledAttributes[]=decreto/data_esecutivita
DisabledAttributes[]=decreto/informazioni_esecutivita
DisabledAttributes[]=decreto/data_archiviazione
DisabledAttributes[]=decreto/stato
DisabledAttributes[]=decreto/pubblicazione
DisabledAttributes[]=decreto/numero_protocollo
DisabledAttributes[]=decreto/testo
DisabledAttributes[]=decreto/proponente
DisabledAttributes[]=decreto/numero_seduta
DisabledAttributes[]=decreto/riferimento
DisabledAttributes[]=decreto/provvedimenti_collegati
DisabledAttributes[]=decreto/classificazione_tipologia
DisabledAttributes[]=decreto/tipologia_trasparenza
DisabledAttributes[]=decreto/allegati
# -- Campi da escludere per agenzie
DisabledAttributes[]=agenzia/data
DisabledAttributes[]=agenzia/data_pubblicazione
DisabledAttributes[]=agenzia/data_esecutivita
DisabledAttributes[]=agenzia/informazioni_esecutivita
DisabledAttributes[]=agenzia/data_archiviazione
DisabledAttributes[]=agenzia/stato
DisabledAttributes[]=agenzia/pubblicazione
DisabledAttributes[]=agenzia/numero_protocollo
DisabledAttributes[]=agenzia/testo
DisabledAttributes[]=agenzia/proponente
DisabledAttributes[]=agenzia/numero_seduta
DisabledAttributes[]=agenzia/riferimento
DisabledAttributes[]=agenzia/provvedimenti_collegati
DisabledAttributes[]=agenzia/classificazione_tipologia
DisabledAttributes[]=agenzia/tipologia_trasparenza
DisabledAttributes[]=agenzia/allegati


# -- Campi da escludere per strutture
DisabledAttributes[]=struttura_organizzativa/descrizione_breve
DisabledAttributes[]=struttura_organizzativa/email
DisabledAttributes[]=struttura_organizzativa/fax
DisabledAttributes[]=struttura_organizzativa/indirizzo
DisabledAttributes[]=struttura_organizzativa/pec
DisabledAttributes[]=struttura_organizzativa/orari
DisabledAttributes[]=struttura_organizzativa/sito_web
DisabledAttributes[]=struttura_organizzativa/telefono
DisabledAttributes[]=struttura_organizzativa/telefono2
*/?>